// Access Token Constants
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const REMOVE_ACCESS_TOKEN = 'REMOVE_ACCESS_TOKEN';

// Auth/Login Constants
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// Onboarding Handlers
export const SIGNUP_HANDLER = 'SIGNUP_HANDLER';
export const TEXTINPUT_HANDLER = 'TEXTINPUT_HANDLER';
export const CHECKBOX_HANDLER = 'CHECKBOX_HANDLER';
export const CHECKBOXNESTED_HANDLER = 'CHECKBOXNESTED_HANDLER';

// Update Profile Constants
export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_ERROR = 'UPDATE_ERROR';

export const ASSIGN_GITHUB_PROFILE = 'ASSIGN_GITHUB_PROFILE';

// Team Constants
export const CREATE_TEAM_REQUEST = 'CREATE_TEAM_REQUEST';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
export const CREATE_TEAM_ERROR = 'CREATE_TEAM_ERROR';
