// Access Token Constants
export const SET_ACCESS_TOKEN    = 'SET_ACCESS_TOKEN';
export const REMOVE_ACCESS_TOKEN = 'REMOVE_ACCESS_TOKEN';

// Auth/Login Constants
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR   = 'LOGIN_ERROR';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_ERROR   = 'PROFILE_ERROR';

// Onboarding Handlers
export const SIGNUP_HANDLER    = 'SIGNUP_HANDLER';
export const TEXTINPUT_HANDLER = 'TEXTINPUT_HANDLER';
export const CHECKBOX_HANDLER  = 'CHECKBOX_HANDLER';
export const CHECKBOXNESTED_HANDLER = 'CHECKBOXNESTED_HANDLER';
export const ONBOARD_PROGRESS = 'ONBOARD_PROGRESS';

// Update Profile Constants
export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_ERROR   = 'UPDATE_ERROR';

export const ASSIGN_GITHUB_PROFILE = 'ASSIGN_GITHUB_PROFILE';

// Team Constants
export const TEAM_REQUEST = 'TEAM_REQUEST';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
export const SINGLE_TEAM_SUCCESS = 'SINGLE_TEAM_SUCCESS';
export const TEAM_LIST_SUCCESS = 'TEAM_LIST_SUCCESS';
export const TEAM_ADD_MEMBER_SUCCESS = 'TEAM_ADD_MEMBER_SUCCESS';
export const TEAM_ERROR = 'TEAM_ERROR';

// Searching for other users
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR   = 'SEARCH_ERROR';
