module.exports = {
  id: '123456',
  displayName: 'Phil Murray',
  username: 'pmurray',
  profileUrl: 'https://github.com/pmurray',
  emails: [ { value: 'phil@philmurray.com' } ],
  provider: 'github',
  _json: {
    login: 'pmurray',
    id: 123456,
    avatar_url: 'http://fillmurray.com/200/300',
    gravatar_id: '',
    url: 'https://api.github.com/users/pmurray',
    html_url: 'https://github.com/pmurray',
    followers_url: 'https://api.github.com/users/pmurray/followers',
    following_url: 'https://api.github.com/users/pmurray/following{/other_user}',
    gists_url: 'https://api.github.com/users/pmurray/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/pmurray/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/pmurray/subscriptions',
    organizations_url: 'https://api.github.com/users/pmurray/orgs',
    repos_url: 'https://api.github.com/users/pmurray/repos',
    events_url: 'https://api.github.com/users/pmurray/events{/privacy}',
    received_events_url: 'https://api.github.com/users/pmurray/received_events',
    type: 'User',
    site_admin: false,
    name: 'Phil Murray',
    company: null,
    blog: 'http://pmurray.github.io/',
    location: 'America',
    email: 'phil@philmurray.com',
    hireable: true,
    bio: 'I\'m Phil Murray.',
    public_repos: 30,
    public_gists: 11,
    followers: 2,
    following: 1,
    created_at: '2010-08-04T21:47:31Z',
    updated_at: '2017-07-18T04:14:48Z'
  }
};
